version: '3.8'

services:
  supervisor:
    image: xprobe/xorbits:v0.8.2-cuda12.5-py3.12
    restart: always
    ports:
      - "9990:9990"
      - "9991:9991"
    #volumes:
      #- f:/models/xinference/:/root/.xinference
      #- f:/models/huggingface:/root/.cache/huggingface
      #- f:/models/modelscope:/root/.cache/modelscope
#    volumes:
#      # Replace <xinference_home> with your xinference home path on the host machine
#      - <xinference_home>:/root/.xinference
#      # Replace <huggingface_cache_dir> with your huggingface cache path, default is
#      # <home_path>/.cache/huggingface
#      - <huggingface_cache_dir>:/root/.cache/huggingface
#      # If models are downloaded from modelscope, replace <huggingface_cache_dir> with
#      # your modelscope cache path, default is <home_path>/.cache/modelscope
#      - <modelscope_cache_dir>:/root/.cache/modelscope
#    environment:
#      # add envs here. Here's an example, if you want to download model from modelscope
#      - XINFERENCE_MODEL_SRC=modelscope
    environment:
      - HF_ENDPOINT=https://hf-mirror.com
      - XINFERENCE_MODEL_SRC=huggingface
    command: /opt/conda/bin/python -m xorbits.supervisor --host 0.0.0.0 -p 9991 -w 9990
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              count: all